<?php
 $plugin_name['straindb']='StrainDB plug-in';
 $plugin_title['straindb']='StrainDB';
 $plugin_version['straindb']='1.0.2';
 $plugin_dir['straindb']='straindb/';
 $plugin_db['straindb']='db_straindb';
 $plugin_level['straindb']=3;
 $plugin_status['straindb']=true;
 $plugin_desc['straindb']['en_US']='Strain database';
 $plugin_desc['straindb']['fr_FR']='Base de donn&eacute;es de souches';     
 bindtextdomain('straindb', $_SERVER['DOCUMENT_ROOT'] . $base_url . 'straindb/locale');
?>
