<?php
 $plugin_name['plasmiddb']='PlasmidDB plug-in';
 $plugin_title['plasmiddb']='PlasmidDB';
 $plugin_version['plasmiddb']='1.0.3';
 $plugin_dir['plasmiddb']='plasmiddb/';
 $plugin_db['plasmiddb']='db_plasmiddb';
 $plugin_level['plasmiddb']=2;
 $plugin_status['plasmiddb']=true;
 $plugin_desc['plasmiddb']['en_US']='Plasmids and vectors database';
 $plugin_desc['plasmiddb']['fr_FR']='Base de donn&eacute;es de plasmides et de vecteurs';
 bindtextdomain('plasmiddb', $_SERVER['DOCUMENT_ROOT'] . $base_url . 'plasmiddb/locale');     
?>
