<?php
 $plugin_name['seeddb']='SeedDB plug-in';
 $plugin_title['seeddb']='SeedDB';
 $plugin_version['seeddb']='1.2.2';
 $plugin_dir['seeddb']='seeddb/';
 $plugin_db['seeddb']='db_seeddb';
 $plugin_level['seeddb']=4;
 $plugin_status['seeddb']=true;
 $plugin_desc['seeddb']['en_US']='Seeds database';
 $plugin_desc['seeddb']['fr_FR']='Base de donn&eacute;es de graines';
 bindtextdomain('seeddb', $_SERVER['DOCUMENT_ROOT'] . $base_url . 'seeddb/locale');
?>
