<?php
 $plugin_name['oligodb']='OligoDB plug-in';
 $plugin_title['oligodb']='OligoDB';
 $plugin_version['oligodb']='1.4.4';
 $plugin_dir['oligodb']='oligodb/';
 $plugin_db['oligodb']='db_oligodb';
 $plugin_level['oligodb']=1;
 $plugin_status['oligodb']=true;
 $plugin_desc['oligodb']['en_US']='Synthetic oligonucleotide database';
 $plugin_desc['oligodb']['fr_FR']='Base de donn&eacute;es d&#39;oligonucl&eacute;otides de synth&egrave;se';
 bindtextdomain('oligodb', $_SERVER['DOCUMENT_ROOT'] . $base_url . 'oligodb/locale');
?>
